default:
    trainer: ppo
    batch_size: 128
    beta: 1.0e-2
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e6
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

RollerBehavior:
    normalize: true
    lambd: 0.95
    num_epoch: 8
    summary_freq: 1000
    time_horizon: 100
    batch_size: 10
    buffer_size: 100
    hidden_units: 255
    num_layers: 2
    beta: 5.0e-3
    max_steps: 1.0e7
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

RollerBehavior1:
    normalize: true
    lambd: 0.95
    num_epoch: 8
    summary_freq: 1000
    time_horizon: 100
    batch_size: 10
    buffer_size: 100
    hidden_units: 256
    num_layers: 2
    beta: 5.0e-3
    max_steps: 1.0e7
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99